# Generated by Django 2.1.5 on 2019-03-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190202_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tenant',
            field=models.BooleanField(default=False, help_text='When this is true at creation time, this user becomes a tenant under the main'),
        ),
    ]
