# Generated by Django 2.1.5 on 2019-03-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190309_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subdomain',
        ),
    ]
