# Generated by Django 2.1.5 on 2019-03-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_subdomain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproxy',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
