# Generated by Django 2.1.5 on 2019-03-09 14:30

from django.db import migrations, models
import django.db.models.deletion
import os


def create_default_public_schema(apps, schema_editor):
    client = apps.get_model('clients', 'Client')
    if schema_editor.connection.alias == 'default':
        tenant = client(domain_url=os.getenv('MAIN_DOMAIN_URL', 'localhost'), schema_name='public', name='Main Website',
                        paid_until='2040-10-11', on_trial=False)
        tenant.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20190309_1355'),
        ('clients', '0002_auto_20190202_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProxy'),
        ),
        migrations.RunPython(create_default_public_schema, reverse_code=migrations.RunPython.noop)
    ]
