# Generated by Django 2.1.5 on 2019-03-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
